// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandResponseStatus } from "./CommandResponseStatus";

export type CommandResponse<T> = { body: T | null, message: string, status: CommandResponseStatus, };
