[package]
name = "vault"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "desktop/tauri",
    "backend",
    "database/entities",
    "database/migration",
    "gateway"
]

[dependencies]
