[build]
target = "./index.html"

[watch]
ignore = ["./tauri"]

[serve]
port = 1420
open = false


# [[hooks]]
# stage = "build"
# command = "just watch styles"
# command_argument = ["watch","styles"]
