[package]
name = "backend"
version = "0.1.0"
edition = "2021"


[workspace]
members = ["app", "entity", "migration"]


[dependencies]

app = {path ="app"}
tokio = { version = "1.39.2", features = ["full"] }
anyhow = "1.0.86"
