[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
chrono = "0.4.38"
nanoid = "0.4.0"
serde = { version = "1.0.204", features = ["derive"] }
sqlx = "0.8.0"
uuid = "1.10.0"
