[package]
name = "bookmark_hooks"
version = "0.1.0"
edition = "2021"

[dependencies]
bookmark_components = { version = "0.1.0", path = "../components" }
bookmark_state = { version = "0.1.0", path = "../state" }
bookmark_ui_errors = { version = "0.1.0", path = "../errors" }
