// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IpcResponseStatus } from "./IpcResponseStatus";

export type IpcResponse<T> = { body: T, message: string, status: IpcResponseStatus, };
